### ISSUE TITLE
Add PHP 7.3 to docker-php-dev

### ISSUE THREAD

**Issue by henri9813** [nexylan/docker-php-dev#26]
Hello,

PHP 7.3 was released in stable version, it could be interesting to add support for this version.

Regards,

**Comment by soullivaneuh** [comment]
@henri9813 Would you like to contribute?

**Comment by henri9813** [comment]
Yes @Soullivaneuh , 
I'm preparing the PR, i will just have to wait a stable version for xDebug cause it doesnt actually support PHP 7.3 :/ 

There is a "beta version" but it's preferable to wait a stable version.
https://pecl.php.net/package/xdebug
https://xdebug.org/updates.php

Best regards.

**Comment by soullivaneuh** [comment]
xdebug is installed by the docker extension with pecl: https://github.com/nexylan/docker-php-dev/search?q=xdebug&unscoped_q=xdebug

We can try to see if the image is built. An automatic update is on place on this repository, we will get the stable version later. :+1:

**Comment by henri9813** [comment]
Actually, i already tried it but it doesn't work.
 
The compilation of xdebug fail due to php7.3 incompatibility.
